### ISSUE TITLE
Editor Compiling Fails on Mac OS X at calls to ui_add_gadget_button

### ISSUE THREAD

**Issue by kreatordxx** [dxx-rebirth/dxx-rebirth#223]
When I build for the editor I get this output:
```
CXX d1x . similar/editor/eswitch.cpp
similar/editor/eswitch.cpp:334:2: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
    ui_add_gadget_button(w, 155, i, 140, 26, "Remove Trigger", trigger_remove); i += 29;
    ^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
similar/editor/eswitch.cpp:335:2: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
    ui_add_gadget_button(w, 155, i, 140, 26, "Bind Wall", bind_wall_to_trigger); i += 29;
    ^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
similar/editor/eswitch.cpp:336:2: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
    ui_add_gadget_button(w, 155, i, 140, 26, "Bind Matcen", bind_matcen_to_trigger); i += 29;
    ^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
similar/editor/eswitch.cpp:337:2: error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result]
    ui_add_gadget_button(w, 155, i, 140, 26, "All Triggers ON", trigger_turn_all_ON); i += 29;
    ^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
scons: *** [similar/editor/.d1x-rebirth.eswitch.o] Error 1
scons: building terminated because of errors.

```
Looking at ui.h I see this:
```
__attribute_warn_unused_result
std::unique_ptr<UI_GADGET_BUTTON> ui_add_gadget_button(UI_DIALOG * dlg, short x, short y, short w, short h, const char * text, int (*function_to_call)());

```
So the `__attribute_warn_unused_result` would be triggering the errors. Can this be removed? As a button can itself call a function linked to the UI_GADGET_BUTTON when clicked, the return value isn't necessarily required (unless we want to check the button has been pressed using a general dialog handler). Otherwise the editor builds fine.

**Comment by vLKp** [comment]
No, that cannot be removed.  Objects of type `std::unique_ptr<T>` automatically delete the contained pointer when the object is destroyed.  If you ignore the return value, the object (in this case, the `UI_GADGET_BUTTON`) is destroyed when the statement finishes.  At best, this means the button is destroyed before the user ever sees it.  At worst, if the destructor is not sufficient to unlink it from any resources that use it, you will get dangling pointers to freed memory.  I annotated that function and similar ones because the result must be saved in order to keep the gadget alive, but only discovered later on that gcc does not warn for unused results when the type is `std::unique_ptr`.

The editor may **build** fine, but it will *not* **run** fine.  I think it has been wrong since December 2014.  Fixing it has been very low priority since the editor never worked very well for me even when it ran correctly.  It tended to crash on startup if its files were not laid out perfectly, and sometimes died of random stack smash prevention events during use.  I have a patch that saves some of these return values, but I never finished it to save all of them.

**Comment by kreatordxx** [comment]
OK that makes sense, so the pointers to those buttons would need to be retained and dealt with by the dialog handler like the other gadgets, and it sounds like other gadgets are in a similar situation.

I got the editor to work a while ago (before December 2014) and it was pretty buggy, but somewhat functional. What I found cool was being able to switch between the editor and a game - so it effectively became a (somewhat limited) game state editor. One of the reasons I implemented that event based, object oriented window scheme (in C at the time) was so I could make the editor code more object oriented, which I went some way in doing (another reason was so redrawing was done properly). From a brief look I see you've done a lot of work to use C++ features like the array container as well. I'm pretty new to C++ but am particularly interested in its classes/objects feature. I'm thinking about what to work on next and considering working more on the editor as an option.

**Comment by kreatordxx** [comment]
Could you send the patch you mentioned? Thanks.

**Comment by vLKp** [comment]
Posted as [Save some editor gadget pointers](/dxx-rebirth/dxx-rebirth/commit/69eec0d71f395da97db79721b3f911718298af8c).  This does not fix everything, but is a start.

**Comment by kreatordxx** [comment]
Thanks! I'll have a go at the rest.  I'll add a class for the main dialog screen (a bit of work, but will tidy up a lot of those globals hanging out all over the place).

**Comment by kreatordxx** [comment]
See pull request #226.
