### ISSUE TITLE
Runtime bug: Spider bots spawn green claws instead of baby spiders

### ISSUE THREAD

**Issue by JeodC** [dxx-rebirth/dxx-rebirth#742]
### Environment

Hash a6161c031a5b659073695138d2d848b831720078

Built on 11/25/23 using ```scons sdl2=1 sdlmixer=1 opengl=1```

#### Operating System Environment

* [x] Microsoft Windows 10
* [x] Arch

#### CPU environment

* [ ] x86 (32-bit Intel/AMD)
* [x] x86\_64 (64-bit Intel/AMD)
* [ ] ARM (32-bit)
* [x] ARM64 (64-bit; sometimes called AArch64)

#### Game environment

Descent: First Strike (D1X-Rebirth) -- Using Steam files

### Description

Spider bots spawn green claws instead of expected Baby Spiders. This behavior is only present in D1X-Rebirth and does not occur when playing the same mission in D2X-Rebirth.

#### Regression status

Issue does not occur in the 2022/09/29 build available on the DXX-Rebirth website.

### Steps to Reproduce

Fastest test method: load into Level 6 in Descent: First Strike and go through the first two doors to find a Spider bot on your left.

* Engines affected:
  * [x] D1X-Rebirth
  * [ ] D2X-Rebirth

* Game modes affected:
  * [x] Single player
  * [ ] Multiplayer competitive
    * [ ] Anarchy
    * [ ] Team Anarchy
    * [ ] Robo-Anarchy
    * [ ] Capture the Flag
    * [ ] Bounty
  * [ ] Multiplayer cooperative -- Not tested

**Comment by JeodC** [comment]
Speculate related to robot_id, since the lifters are assigned an id of 1 and the baby spiders have an id of 14. Either typo or truncating second digit maybe.

**Comment by vLKp** [comment]
Confirmed that the drop is incorrect, and only in one game.

**Comment by InfernalCore** [comment]
Result of testing: 
Bug introduced with commit 7a183c1 on 2023.07.15. 
It is still present. 

Method: 
Bug reproduced as indicated by JeodC. 
Bisected and narrowed to 2023.07.15. 
There are 10 commits that day. 
Build with commit 7a183c1 is bugged (with all the following ones). 
Previous commit 0867195 does not show this bug (with all the previous ones).

Comments: 
Commit 7a183c1 title says: “Use enum class for robot_id”.
It is quite a massive chunk of serious stuff, so I wonder if this bug may potentially affect other bots, including bosses and matcens.
Note that robot_id{14} does not appear in the code.

Conclusion: 
Better stick with a previous version. 

System: 
Linux Kernel 5.15.0-88-generic x86_64 bits
Linux Mint 21.2 Cinnamon 5.8.4
Intel Core i9-11900K
NVIDIA TU116 [GeForce GTX 1660 SUPER]

Regards.

**Comment by JeodC** [comment]
On further inspection for that commit, one potential cause could be the following lines in fireball.cpp beginning on line 1195:
```
#if defined(DXX_BUILD_DESCENT_I)
				/* ObjId appears to serve as both a polygon_model_index and as
				 * a robot index.
				 */
				const auto rid = static_cast<robot_id>(ObjId[type]);
#elif defined(DXX_BUILD_DESCENT_II)
				const auto rid = static_cast<robot_id>(id);
#endif
```

D1X is the only build to use ObjId[type] as the source of the identifier and casts it to robot_id.

**Comment by InfernalCore** [comment]
I tried this in fireball.cpp of the bugged version 7a183c1 : 

```
#if defined(DXX_BUILD_DESCENT_I)
     //const auto rid = static_cast<robot_id>(ObjId[type]);
      const auto rid = static_cast<robot_id>(id);
#elif defined(DXX_BUILD_DESCENT_II)
     const auto rid = static_cast<robot_id>(id);
#endif
```

The bug (tested as per previous message) seems to disappear. 
The problem is: what else disappears together with it? What should be tested?
After all, (ObjId[type]) should be there for a reason... or not? 
Unfortunately I haven't the faintest idea about what a polygon_model_index should do and why it appears to be mixed with a bot identifier. 
That's why just hacking is not enough, sadly.
Regards.

**Comment by JeodC** [comment]
> I tried this in fireball.cpp of the bugged version [7a183c1](https://github.com/dxx-rebirth/dxx-rebirth/commit/7a183c18d909e6af5a39b95955afd856f2c2a02c) :
> 
> ```
> #if defined(DXX_BUILD_DESCENT_I)
>      //const auto rid = static_cast<robot_id>(ObjId[type]);
>       const auto rid = static_cast<robot_id>(id);
> #elif defined(DXX_BUILD_DESCENT_II)
>      const auto rid = static_cast<robot_id>(id);
> #endif
> ```
> 
> The bug (tested as per previous message) seems to disappear. The problem is: what else disappears together with it? What should be tested? After all, (ObjId[type]) should be there for a reason... or not? Unfortunately I haven't the faintest idea about what a polygon_model_index should do and why it appears to be mixed with a bot identifier. That's why just hacking is not enough, sadly. Regards.

And in the current build, it starts on line 1200:
```
#if defined(DXX_BUILD_DESCENT_I)
				/* ObjId appears to serve as both a polygon_model_index and as
				 * a robot index.
				 */
				const auto rid = static_cast<robot_id>(ObjId[underlying_value(type)]);
#elif defined(DXX_BUILD_DESCENT_II)
				const auto rid = static_cast<robot_id>(id);
#endif
```

Which could mean the bug was fixed at this point but there is a second cause elsewhere.

**Comment by InfernalCore** [comment]
It could mean so. 
However, let's work on a6161c0 (2023.11.11) affected by the same bug. 
We replace (ObjId[underlying_value(type)]);  with (id).
This fixes the bug again. 

```
#if defined(DXX_BUILD_DESCENT_I)
		//const auto rid = static_cast<robot_id>(ObjId[underlying_value(type)]);
                const auto rid = static_cast<robot_id>(id);
#elif defined(DXX_BUILD_DESCENT_II)
		const auto rid = static_cast<robot_id>(id);
#endif

```

So maybe that (ObjId[underlying_value(type)]) was put there for another good reason, not in relation with this specific bug (because it does not fix it, it would not have passed the test). 
Another regression analysis is needed to find out when (ObjId[underlying_value(type)]) was added, and maybe understand why.
I think I can do this search after xmas. 
But I'm still curious to see what happens leaving just (id) there. Maybe I should play a lot of Descent... mmh... well, yes, why not : )
...the plot thickens...

**Comment by JeodC** [comment]
If you want to understand why then you might try cracking open Level 6 in the descent editor and check robot properties. ;)

**Comment by InfernalCore** [comment]
As per DLE, in D1 level 6 there are 5 Spiders (id=2). 
According to their properties, bots don't spawn bots.  
Maybe is a problem with the editor, or due to the way bot spawning is managed in D1.  

Comparing side by side (with diff or meld) the two files fireball.cpp just before and after the bug inception, not so many lines are changed, just about nine or ten lines. The problem should be hidden somewhere here. 

There is also a line concerning the Bandit (hence D2), also changed.

**Comment by JeodC** [comment]
A quick read of fireball.cpp commit history for [7a183c1](https://github.com/dxx-rebirth/dxx-rebirth/commit/7a183c18d909e6af5a39b95955afd856f2c2a02c) shows that robot_id was created to consolidate several different special bot definitions into one class. A change to the above line to fix the baby spider bug may impact other special circumstances like the boss robot in L27 that creates other robots as well as the supervisor robot (referred to as brain in code) and the gopher robot (referred to as toaster in code). At the very least that should help narrow down where to test it.

**Comment by vLKp** [comment]
https://github.com/dxx-rebirth/dxx-rebirth/issues/742#issuecomment-1866698281 :

> It is quite a massive chunk of serious stuff, so I wonder if this bug may potentially affect other bots, including bosses and matcens.

Yes, it likely affects everything in Descent 1 that uses `drop_robot_egg`, which is called by `object_create_robot_egg`.

---

https://github.com/dxx-rebirth/dxx-rebirth/issues/742#issuecomment-1867001729 :

> On further inspection for that commit, one potential cause could be the following lines in fireball.cpp beginning on line 1195:

The strange part is that if you look at the diff for 7a183c18d909e6af5a39b95955afd856f2c2a02c, this appears to be a reasonable change:

```diff
@@ -1196,11 +1196,12 @@ static bool drop_robot_egg(const d_robot_info_array &Robot_info, const int type,
                /* ObjId appears to serve as both a polygon_model_index and as
                 * a robot index.
                 */
-               const auto robot_id = static_cast<unsigned>(ObjId[type]);
+               const auto rid = static_cast<robot_id>(ObjId[type]);
 #elif defined(DXX_BUILD_DESCENT_II)
-               const auto robot_id = id;
+               const auto rid = static_cast<robot_id>(id);
 #endif
-               const auto &&objp = robot_create(Robot_info, id, segnum, new_pos, &vmd_identity_matrix, Polygon_models[Robot_info[robot_id].model_num].rad, ai_behavior::AIB_NORMAL);
+               auto &robptr = Robot_info[rid];
+               const auto &&objp = robot_create(Robot_info, rid, segnum, new_pos, &vmd_identity_matrix, Polygon_models[robptr.model_num].rad, ai_behavior::AIB_NORMAL);
                if (objp == object_none)
                    break;
                auto &obj = *objp;
```

The type that the `static_cast` produces is updated, but both the before and after code reference the same global `ObjId` using the same index variable.  The retrieved value is 1 byte wide, so the `static_cast` cannot truncate it.

---

https://github.com/dxx-rebirth/dxx-rebirth/issues/742#issuecomment-1868249526 :

> After all, (ObjId[type]) should be there for a reason... or not?

Maybe or maybe not.  This traces all the way to the beginning.  `0.51-d1x` has:

```
                objnum = obj_create(OBJ_ROBOT, objp->contains_id, objp->segnum, &new_pos, &vmd_identity_matrix, Polygon_models[Robot_info[ObjId[objp->contains_type]].model_num].rad, CT_AI, MT_PHYSICS, RT_POLYOBJ);
```

Looking at it again, I think I see the problem.  The issue is not with `ObjId`.  The issue is with an incorrect simplification.  In the good commit, the second argument to `robot_create` is `id`; in the bad commit, the second argument is `rid`.  In Descent 1, `rid` comes from `ObjId` (and so you might expect you could use it as an ID), where `id` comes from the caller.  In Descent 2, `rid` is an alias for `id`, so the commit has no effect on that argument.  Therefore, I think the right fix is to revert that simplification and use `id` as the second argument to `robot_create`, in both games.

**Comment by vLKp** [comment]
On further investigation, @InfernalCore was correct in ( https://github.com/dxx-rebirth/dxx-rebirth/issues/742#issuecomment-1868305771 ).  The use of `ObjId` appears to be incorrect.  I believe Descent 1 has always had a bug where it used the wrong robot's radius here, but that is subtle and hard for players to notice.  That bug led me to use a value that was not a robot_id as if it was one.  My initial attempt at a fix was to change the parameter to `robot_create`.  That resulted in the game creating robots that acted like the baby spider (correct), but _looked_ like the lifter (incorrect!).  Instead, the above commit switches Descent 1 to use the Descent 2 logic here, which causes Descent 1 to produce a robot that both looks and acts like the expected baby spider.

Please sync to `master` and retest.  Reopen if you still see problems.
